FORMAT: 1A9
HOST: https://sandbox.scurri.co.uk/api/v1

# Scurri API

The Scurri Platform API is a RESTful web service that offers import
and update functionality for consignments, documents and manifests.

Scurri have API’s available for [delivery options at checkout](https://scurrideliveryoptionsapi.docs.apiary.io/#)
and [delivery locations](https://deliverylocationsapi.docs.apiary.io/#).
There is a tracking API available for pulling back tracking data, information on this is available on request.

## HTTP Codes

HTTP codes are used to differentiate between successful and failed
responses. As per the HTTP standard: 20x codes are for successful
requests, 40x codes for errors with validation or permissions, 50x
codes for unexpected internal server errors.


## Authentication

All requests must be authenticated using either [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication#Client_side) or API token-based authentication.
If you have been provided with an API token, you should use token-based authentication.

### Basic Auth

With Basic Auth, you have to send the username and password **base64-encoded** in the standard Basic manner, e.g.
`Authorization: Basic YXBpdGVzdDphcGkgcGFzc3dvcmQgdGVzdA==`.

Here is some sample code in Python to generate the value of the header:

```python
>>> import base64
>>> username = 'apitest'
>>> password = 'api-test-password'
>>> print base64.b64encode(username + ':' + password)
YXBpdGVzdDphcGktdGVzdC1wYXNzd29yZA==
```

### API Token

With API token-based authentication, you must include the token in the Authorization header as an API token, e.g.
`Authorization: token YOUR_API_TOKEN`.

Failed requests will return a 401 HTTP code with `WWW-Authenticate: Basic` response header.

## Request format

All body payloads must be in JSON format, unless stated otherwise.

As a result, the `Content-Type` header must be set to `application/json`.

## Using the Scurri API

### General

The most important features of the Scurri API are:

- Importing consignments
- Getting the necessary documents (labels and/or commercial invoices)
- Manifesting consignments

The Scurri API works only on top of HTTPS, so that the connection is
encrypted.

The Scurri API is currently at version 1. This means that all URLs
should be prefixed with the path `/v1/`.

### Concepts

Each company is assigned a **slug**, which is an identifier for this
company and is used in all URLs of this API. The slug can be found in
the URLs used in Scurri: it is the value after the path `company` and
until the next forward slash (`/`). That is, in the URL
`/company/my-company/manifests` the slug is the value `my-company`.

Each consignment is identified by a unique **identifier** which you
can optionally provide. This identifier should be unique across all of your
consignments. If all of your orders correspond to a single
consignment, then the order number is a good candidate for this. If
you do not provide an identifier for the consignments, scurri will
generate a unique id.

### Consignment Lifecycle

#### Importing consignments

The first step is to import your consignments into Scurri. They can be imported individually (one by one) or as part of a batch. Scurri has optimized the
import process to support importing thousands of consignments in one
API call.

#### Getting the label for a consignment

After a consignment has been imported, Scurri will automatically
allocate it to a carrier and a service based on the shipment rules you
have defined in our user interface, alternatively you can specificy these values in the API (and in doing so overwrite any shipment rules that may already be set up).

At this point Scurri will try to validate that the consignment meets the
criteria for using the specified carrier and service, e.g. typically these would be the weight limits,
dimension limits and destination restrictions.

If the consignment does not fail the validation step you can download
its label(s) and any customs documentation required, either as PDF documents or
PNG. The latter is useful for embedding the label(s) in another document.
After the label has been generated, the tracking number for the consignment is available in the consignment details.

If, on the other hand, this validation had failed (that it exceeds the
weight, dimension or destination limits and restrictions) then you
would get an error back with the reason the validation failed.

#### Manifesting consignments

The last step is marking the consignments as manifested. When you do
this, Scurri will generate the manifest documentation that you may
have to provide to the carrier and at the same time notify the
carrier. Note - Once you've manifested a conisgnment it will no longer
be available for editing.

# Carriers [/company/{company_slug}/carriers/]

The Carriers API allows you to query Scurri for the carriers that are
enabled in your account.

The result contains the identifier for each carrier, which you can use
in the rest of the API calls, whenever a **Carrier** needs to be
specified.  The identifier will never change, so this can be called
once to get the values.

## List all the carriers for the logged in user [GET]

+ Authorization (Basic)
+ Parameters
    + company_slug: `api-test-company` (string) - The slug of your company in Scurri.
+ Request
    + Headers

            Authorization: Basic YXBpdGVzdDphcGkgcGFzc3dvcmQgdGVzdA==

+ Response 200 (application/json)

            [
                {
                    "identifier": "Generic Carrier",
                    "name": "Generic Carrier"
                }
            ]

# Carrier Services [/company/{company_slug}/carrierservices/]

The CarrierServices API allows you to retrieve a list of services that
have been enabled in your account.

The result contains the identifier for each service, which you can use
in the rest of the API calls, whenever a **Service** needs to be
specified.

## List all the carrier services for the logged in user [GET]
This is an example of the Carrier Services call with the response.

Test URL: `https://sandbox.scurri.co.uk/api/v1/company/scurri-live-test/carrierservices`

+ Parameters
    + company_slug: `api-test-company` (string) - The slug of your company in Scurri.
    + enhancements: (boolean, optional) - Whether to include `enhancements` in the response
        + Default: false
    + package_types: (boolean, optional) - Whether to include `package types` in the response
        + Default: false
+ Request
    + Headers

            Authorization: Basic YXBpdGVzdDphcGkgcGFzc3dvcmQgdGVzdA==

+ Response 200 (application/json)

            [
                {
                    "carrier_id": "Generic Carrier",
                    "identifier": "Generic Carrier|Generic International Service GCINT",
                    "name": "Generic International Service"
                },
                {
                    "carrier_id": "Generic Carrier",
                    "identifier": "Generic Carrier|Generic Domestic Service GDOM",
                    "name": "Generic Domestic Service"
                }
            ]

## Example of carrier services for the logged in user with options[GET /company/{company_slug}/carrierservices{?enhancements,package_types}]
This is an example of the Carrier Services call with the response including Enhancements and Package Types.

Test URL: `https://sandbox.scurri.co.uk/api/v1/company/scurri-live-test/carrierservices?enhancements=true&package_types=true`

The available Enhancements and Package Types will be returned in the response

+ Parameters
    + company_slug: `api-test-company` (string) - The slug of your company in Scurri.
    + enhancements: true (boolean, optional) - Whether to include `enhancements` in the response
        + Default: false
    + package_types: true (boolean, optional) - Whether to include `package types` in the response
        + Default: false
+ Request
    + Headers

            Authorization: Basic YXBpdGVzdDphcGkgcGFzc3dvcmQgdGVzdA==

+ Response 200 (application/json)

            [
                {
                    "carrier_id": "Generic Carrier",
                    "identifier": "Generic Carrier|Generic International Service GCINT",
                    "name": "Generic International Service",
                    "enhancements":[],
                    "package_types":[]
                },
                {
                    "carrier_id": "Generic Carrier",
                    "identifier": "Generic Carrier|Generic Domestic Service GDOM",
                    "name": "Generic Domestic Service",
                    "enhancements":[],
                    "package_types":[]
                }
            ]

# Warehouses [/company/{company_slug}/warehouses/]

The Warehouses API allows you to retrieve a list of warehouses that
you have access to (within a company).

The result contains the identifier for each warehouse, which you can
use in the rest of the API calls, whenever a **Warehouse** needs to be
specified.

## List all the warehouses the user has access to [GET]

+ Parameters
    + company_slug: `api-test-company` (string) - The slug of your company in Scurri.
+ Request
    + Headers

            Authorization: Basic YXBpdGVzdDphcGkgcGFzc3dvcmQgdGVzdA==

+ Response 200 (application/json)

            [
                {
                    "identifier": "api-test-company|Test Warehouse",
                    "name": "Test Warehouse"
                }
            ]

# Group Consignments

## Consignments Collection [/company/{company_slug}/consignments/]

This group of API calls allow you to interact with your consignments
in Scurri. You can list and search through them, create new ones, get
their status and print the necessary documentation (labels and custom
invoices, when needed).

+ Parameters
    + company_slug: `api-test-company` (string) - The slug of your company in Scurri.

### Get the list of created consignments [GET /company/{company_slug}/consignments/{?offset,limit,identifier,status}]

You can get use this API call to retrieve the list of consignments in
Scurri.

Pagination is provided via the `offset` and `limit` GET parameters.

For the `offset`, we don't use an integer value but instead use the last
`identifier` of the current batch. The `next` value returned with the
response body contains a URL you can use to retrieve the next batch.

Example offset URL: `https://sandbox.scurri.co.uk/api/v1/company/test-company/consignments/?offset=000ed1bfb93c43319ec79247f50dfd3c`

You can also use this API call to search for consignments using
specific criteria, either for a specific `identifier` or for
consignments of a specific `status`.
This API cannot be used to search for multiple consignments by their identifiers,
you may only search for a single consignment by identifier.

The `Despatched`, `Delivered` and `Exception` statuses are only available if Tracking has been enabled on your account.

+ Parameters
    + company_slug: `api-test-company` (string) - The slug of your company in Scurri.
    + offset (string,optional) - The offset for any pagination. This is the string identifier of the last consignment entry in the current batch.
        + Default: ''
    + limit (int,optional) - How many results to return for a request.
        + Default: 10
    + identifier: `myidentifier` (string,optional) - Search for the consignment with the given identifier.
    + status: `Unallocated` (enum[string],optional) - Search for consignments with a specific status.
        + Members
             + `Unallocated`
             + `Allocated`
             + `Printed`
             + `Manifested`
             + `Despatched`
             + `Delivered`
             + `Exception`
             + `Cancelled`


+ Request
    + Headers

                Authorization: Basic YXBpdGVzdDphcGkgcGFzc3dvcmQgdGVzdA==

+ Response 200 (application/json)

            {
                "count": 1,
                "next": null,
                "results": [
                    {
                        "carrier": "Generic Carrier",
                        "consignment_number": null,
                        "create_date": "2016-03-28T11:53:31+0000",
                        "expected_delivery_date": null,
                        "currency": "GBP",
                        "current_status": {
                            "rejection_reason": null,
                            "short_form": "Allocated",
                            "status": "Carrier and service allocated"
                        },
                        "delivery_instructions": "",
                        "identifier": "8a12630db404424b943e131ce4ee3976",
                        "invoice": {
                            "incoterm": ""
                        },
                        "options": {
                            "package_type": null
                        },
                        "order_number": "8384832",
                        "order_value": null,
                        "packages": [
                            {
                                "description": "Jeans",
                                "reference": "CustomerPackageReference1",
                                "height": 0.5,
                                "items": [
                                    {
                                        "country_of_origin": "GB",
                                        "harmonisation_code": "5201",
                                        "name": "Jeans",
                                        "quantity": 1,
                                        "sku": "822 JEANS",
                                        "value": 25.55,
                                        "weight": 1.0
                                    }
                                ],
                                "length": 10.0,
                                "tracking_number": null,
                                "width": 12.2
                            }
                        ],
                        "recipient": {
                            "address": {
                                "address1": "Innovation House",
                                "address2": "The Bullring",
                                "address3": "",
                                "city": "Wexford",
                                "country": "IE",
                                "postcode": "Y35 DW6E",
                                "state": "Wexford",
                                "store_code": ""
                            },
                            "company_name": "Scurri",
                            "contact_number": "072 8848292234",
                            "email_address": "john@scurri.com",
                            "first_name": "",
                            "last_name": "John Doe",
                            "name": "John Doe"
                        },
                        "rules_package_type": "Shipment 44147 : None",
                        "service": "Generic International Service",
                        "service_id": "Generic Carrier|Generic International Service GCINT",
                        "shipping_method": "",
                        "tracking_url": "",
                        "warehouse_id": "api-test-company|Test Warehouse"
                    }
                ]
            }

### Example Offset with Multiple Pages [GET /company/{company_slug}/consignments/{?offset,limit,status}]

This is an example `offset` with the response.

Test URL: `https://sandbox.scurri.co.uk/api/v1/company/scurri-live-test/consignments/?offset=TEST2893&status=Printed`

As you can see, in the `next` field, it returns the link to next batch.
The next returns `null` if it's the last batch.
Also the count decreases as you traverse using the `next` links.

The `Despatched`, `Delivered` and `Exception` statuses are only available if Tracking has been enabled on your account.

+ Parameters
    + company_slug: `api-test-company` (string) - The slug of your company in Scurri.
    + offset: TEST2893 (string,optional) - The offset for any pagination. This is the string identifier of the last consignment entry in the current batch.
        + Default: ''
    + limit: (int,optional) - How many results to return for a request.
        + Default: 10
    + identifier: (string,optional) - Search for the consignment with the given identifier.
    + status: Printed (enum[string],optional) - Search for consignments with a specific status.
        + Members
             + `Unallocated`
             + `Allocated`
             + `Printed`
             + `Manifested`
             + `Despatched`
             + `Delivered`
             + `Exception`
             + `Cancelled`

+ Request
    + Headers

                Authorization: Basic YXBpdGVzdDphcGkgcGFzc3dvcmQgdGVzdA==

+ Response 200 (application/json)

{
  "count": 23,
  "next": "https://sandbox.scurri.co.uk/api/v1/company/scurri-live-test/consignments/?offset=TEST5838&status=Printed",
  "results": [
    {
      "identifier": "TEST3019",
      "order_number": "TEST3019",
      "create_date": "2017-05-24T12:03:12+0000",
      "expected_delivery_date": "2017-05-28",
      "service_id": "Generic Carrier|Generic International Service GCINT",
      "warehouse_id": "scurri-live-test|TechHub @Campus",
      "current_status": {
        "short_form": "Printed",
        "status": "Labels printed, shipment ready to manifest.",
        "rejection_reason": null
      },
      "recipient": {
        "name": "John Smith",
        "first_name": "",
        "last_name": "John Smith",
        "company_name": "Scurri",
        "email_address": "example-email@scurri.com",
        "contact_number": "0123456789",
        "address": {
          "address1": "Innovation House",
          "address2": "The Bullring",
          "address3": "",
          "city": "Wexford",
          "state": "Wexford",
          "postcode": "Y35 DW6E",
          "country": "IE",
          "store_code": ""
        },
        "tax_identifier": ""
      },
      "packages": [
        {
          "description": "Sample Product",
          "tracking_number": "9389491",
          "width": 3,
          "height": 1,
          "length": 1,
          "items": [
            {
              "name": "Sample Product",
              "quantity": 2,
              "sku": "PRO123",
              "country_of_origin": "GB",
              "harmonisation_code": "71131900",
              "weight": 2,
              "value": 5
            }
          ]
        }
      ],
      "invoice": {
        "incoterm": ""
      },
      "delivery_instructions": "Leave in the garden shed",
      "currency": "EUR",
      "options": {
        "package_type": null
      },
      "shipping_method": "",
      "consignment_number": "000000000008108293",
      "order_value": null,
      "tracking_url": "",
      "service": "Generic International Service",
      "carrier": "Generic Carrier",
      "rules_package_type": "",
      "shipping_date": null,
      "custom_field_1": "CUSTOM1",
      "custom_field_2": "CUSTOM2",
      "custom_field_3": "CUSTOM3",
      "custom_field_4": "CUSTOM4",
      "custom_field_5": "CUSTOM5",
      "export_customs": {}
    },
    {
      "identifier": "TEST3027",
      "order_number": "TEST3027",
      "create_date": "2017-05-24T12:03:45+0000",
      "expected_delivery_date": "2017-05-28",
      "service_id": "Generic Carrier|Generic International Service GCINT",
      "warehouse_id": "scurri-live-test|TechHub @Campus",
      "current_status": {
        "short_form": "Printed",
        "status": "Labels printed, shipment ready to manifest.",
        "rejection_reason": null
      },
      "recipient": {
        "name": "John Smith",
        "first_name": "",
        "last_name": "John Smith",
        "company_name": "Scurri",
        "email_address": "example-email@scurri.com",
        "contact_number": "0123456789",
        "address": {
          "address1": "Innovation House",
          "address2": "The Bullring",
          "address3": "",
          "city": "Wexford",
          "state": "Wexford",
          "postcode": "Y35 DW6E",
          "country": "IE",
          "store_code": ""
        },
        "tax_identifier": ""
      },
      "packages": [
        {
          "description": "Sample Product",
          "tracking_number": "9389542",
          "width": 1,
          "height": 2,
          "length": 3,
          "items": [
            {
              "name": "Sample Product",
              "quantity": 2,
              "sku": "PRO123",
              "country_of_origin": "GB",
              "harmonisation_code": "71131900",
              "weight": 0,
              "value": 5
            }
          ]
        }
      ],
      "invoice": {
        "incoterm": ""
      },
      "delivery_instructions": "Leave in the garden shed",
      "currency": "EUR",
      "options": {
        "package_type": null
      },
      "shipping_method": "",
      "consignment_number": "000000000008108343",
      "order_value": null,
      "tracking_url": "",
      "service": "Generic International Service",
      "carrier": "Generic Carrier",
      "rules_package_type": "",
      "shipping_date": null,
      "custom_field_1": "CUSTOM1",
      "custom_field_2": "CUSTOM2",
      "custom_field_3": "CUSTOM3",
      "custom_field_4": "CUSTOM4",
      "custom_field_5": "CUSTOM5",
      "export_customs": {}
    },
    {
      "identifier": "TEST334",
      "order_number": "TEST334",
      "create_date": "2017-05-24T12:03:43+0000",
      "expected_delivery_date": "2017-05-28",
      "service_id": "Generic Carrier|Generic International Service GCINT",
      "warehouse_id": "scurri-live-test|TechHub @Campus",
      "current_status": {
        "short_form": "Printed",
        "status": "Labels printed, shipment ready to manifest.",
        "rejection_reason": null
      },
      "recipient": {
        "name": "John Smith",
        "first_name": "",
        "last_name": "John Smith",
        "company_name": "Scurri",
        "email_address": "example-email@scurri.com",
        "contact_number": "0123456789",
        "address": {
          "address1": "Innovation House",
          "address2": "The Bullring",
          "address3": "",
          "city": "Wexford",
          "state": "Wexford",
          "postcode": "Y35 DW6E",
          "country": "IE",
          "store_code": ""
        },
        "tax_identifier": ""
      },
      "packages": [
        {
          "description": "Sample Product",
          "tracking_number": "9389538",
          "width": 2,
          "height": 1,
          "length": 1,
          "items": [
            {
              "name": "Sample Product",
              "quantity": 0,
              "sku": "PRO123",
              "country_of_origin": "GB",
              "harmonisation_code": "71131900",
              "weight": 1,
              "value": 79
            }
          ]
        }
      ],
      "invoice": {
        "incoterm": ""
      },
      "delivery_instructions": "Leave in the garden shed",
      "currency": "EUR",
      "options": {
        "package_type": null
      },
      "shipping_method": "",
      "consignment_number": "000000000008108339",
      "order_value": null,
      "tracking_url": "",
      "service": "Generic International Service",
      "carrier": "Generic Carrier",
      "rules_package_type": "",
      "shipping_date": null,
      "custom_field_1": "CUSTOM1",
      "custom_field_2": "CUSTOM2",
      "custom_field_3": "CUSTOM3",
      "custom_field_4": "CUSTOM4",
      "custom_field_5": "CUSTOM5",
      "export_customs": {}
    },
    {
      "identifier": "TEST3618",
      "order_number": "TEST3618",
      "create_date": "2017-05-24T12:03:44+0000",
      "expected_delivery_date": "2017-05-28",
      "service_id": "Generic Carrier|Generic International Service GCINT",
      "warehouse_id": "scurri-live-test|TechHub @Campus",
      "current_status": {
        "short_form": "Printed",
        "status": "Labels printed, shipment ready to manifest.",
        "rejection_reason": null
      },
      "recipient": {
        "name": "John Smith",
        "first_name": "",
        "last_name": "John Smith",
        "company_name": "Scurri",
        "email_address": "example-email@scurri.com",
        "contact_number": "0123456789",
        "address": {
          "address1": "Innovation House",
          "address2": "The Bullring",
          "address3": "",
          "city": "Wexford",
          "state": "Wexford",
          "postcode": "Y35 DW6E",
          "country": "IE",
          "store_code": ""
        },
        "tax_identifier": ""
      },
      "packages": [
        {
          "description": "Sample Product",
          "tracking_number": "9389539",
          "width": 3,
          "height": 2,
          "length": 1,
          "items": [
            {
              "name": "Sample Product",
              "quantity": 1,
              "sku": "PRO123",
              "country_of_origin": "GB",
              "harmonisation_code": "71131900",
              "weight": 2,
              "value": 55
            }
          ]
        }
      ],
      "invoice": {
        "incoterm": ""
      },
      "delivery_instructions": "Leave in the garden shed",
      "currency": "EUR",
      "options": {
        "package_type": null
      },
      "shipping_method": "",
      "consignment_number": "000000000008108340",
      "order_value": null,
      "tracking_url": "",
      "service": "Generic International Service",
      "carrier": "Generic Carrier",
      "rules_package_type": "",
      "shipping_date": null,
      "custom_field_1": "CUSTOM1",
      "custom_field_2": "CUSTOM2",
      "custom_field_3": "CUSTOM3",
      "custom_field_4": "CUSTOM4",
      "custom_field_5": "CUSTOM5",
      "export_customs": {}
    },
    {
      "identifier": "TEST3939",
      "order_number": "TEST3939",
      "create_date": "2017-05-24T12:03:48+0000",
      "expected_delivery_date": "2017-05-28",
      "service_id": "Generic Carrier|Generic International Service GCINT",
      "warehouse_id": "scurri-live-test|TechHub @Campus",
      "current_status": {
        "short_form": "Printed",
        "status": "Labels printed, shipment ready to manifest.",
        "rejection_reason": null
      },
      "recipient": {
        "name": "John Smith",
        "first_name": "",
        "last_name": "John Smith",
        "company_name": "Scurri",
        "email_address": "example-email@scurri.com",
        "contact_number": "0123456789",
        "address": {
          "address1": "Innovation House",
          "address2": "The Bullring",
          "address3": "",
          "city": "Wexford",
          "state": "Wexford",
          "postcode": "Y35 DW6E",
          "country": "IE",
          "store_code": ""
        },
        "tax_identifier": ""
      },
      "packages": [
        {
          "description": "Sample Product",
          "tracking_number": "9389548",
          "width": 2,
          "height": 1,
          "length": 1,
          "items": [
            {
              "name": "Sample Product",
              "quantity": 1,
              "sku": "PRO123",
              "country_of_origin": "GB",
              "harmonisation_code": "71131900",
              "weight": 3,
              "value": 12
            }
          ]
        }
      ],
      "invoice": {
        "incoterm": ""
      },
      "delivery_instructions": "Leave in the garden shed",
      "currency": "EUR",
      "options": {
        "package_type": null
      },
      "shipping_method": "",
      "consignment_number": "000000000008108348",
      "order_value": null,
      "tracking_url": "",
      "service": "Generic International Service",
      "carrier": "Generic Carrier",
      "rules_package_type": "",
      "shipping_date": null,
      "custom_field_1": "CUSTOM1",
      "custom_field_2": "CUSTOM2",
      "custom_field_3": "CUSTOM3",
      "custom_field_4": "CUSTOM4",
      "custom_field_5": "CUSTOM5",
      "export_customs": {}
    },
    {
      "identifier": "TEST4441",
      "order_number": "TEST4441",
      "create_date": "2017-05-24T12:03:47+0000",
      "expected_delivery_date": "2017-05-28",
      "service_id": "Generic Carrier|Generic International Service GCINT",
      "warehouse_id": "scurri-live-test|TechHub @Campus",
      "current_status": {
        "short_form": "Printed",
        "status": "Labels printed, shipment ready to manifest.",
        "rejection_reason": null
      },
      "recipient": {
        "name": "John Smith",
        "first_name": "",
        "last_name": "John Smith",
        "company_name": "Scurri",
        "email_address": "example-email@scurri.com",
        "contact_number": "0123456789",
        "address": {
          "address1": "Innovation House",
          "address2": "The Bullring",
          "address3": "",
          "city": "Wexford",
          "state": "Wexford",
          "postcode": "Y35 DW6E",
          "country": "IE",
          "store_code": ""
        },
        "tax_identifier": ""
      },
      "packages": [
        {
          "description": "Sample Product",
          "tracking_number": "9389546",
          "width": 2,
          "height": 1,
          "length": 3,
          "items": [
            {
              "name": "Sample Product",
              "quantity": 1,
              "sku": "PRO123",
              "country_of_origin": "GB",
              "harmonisation_code": "71131900",
              "weight": 0,
              "value": 7
            }
          ]
        }
      ],
      "invoice": {
        "incoterm": ""
      },
      "delivery_instructions": "Leave in the garden shed",
      "currency": "EUR",
      "options": {
        "package_type": null
      },
      "shipping_method": "",
      "consignment_number": "000000000008108347",
      "order_value": null,
      "tracking_url": "",
      "service": "Generic International Service",
      "carrier": "Generic Carrier",
      "rules_package_type": "",
      "shipping_date": null,
      "custom_field_1": "CUSTOM1",
      "custom_field_2": "CUSTOM2",
      "custom_field_3": "CUSTOM3",
      "custom_field_4": "CUSTOM4",
      "custom_field_5": "CUSTOM5",
      "export_customs": {}
    },
    {
      "identifier": "TEST4746",
      "order_number": "TEST4746",
      "create_date": "2017-05-24T12:03:52+0000",
      "expected_delivery_date": "2017-05-28",
      "service_id": "Generic Carrier|Generic International Service GCINT",
      "warehouse_id": "scurri-live-test|TechHub @Campus",
      "current_status": {
        "short_form": "Printed",
        "status": "Labels printed, shipment ready to manifest.",
        "rejection_reason": null
      },
      "recipient": {
        "name": "John Smith",
        "first_name": "",
        "last_name": "John Smith",
        "company_name": "Scurri",
        "email_address": "example-email@scurri.com",
        "contact_number": "0123456789",
        "address": {
          "address1": "Innovation House",
          "address2": "The Bullring",
          "address3": "",
          "city": "Wexford",
          "state": "Wexford",
          "postcode": "Y35 DW6E",
          "country": "IE",
          "store_code": ""
        },
        "tax_identifier": ""
      },
      "packages": [
        {
          "description": "Sample Product",
          "tracking_number": "9389553",
          "width": 1,
          "height": 1,
          "length": 1,
          "items": [
            {
              "name": "Sample Product",
              "quantity": 0,
              "sku": "PRO123",
              "country_of_origin": "GB",
              "harmonisation_code": "71131900",
              "weight": 1,
              "value": 56
            }
          ]
        }
      ],
      "invoice": {
        "incoterm": ""
      },
      "delivery_instructions": "Leave in the garden shed",
      "currency": "EUR",
      "options": {
        "package_type": null
      },
      "shipping_method": "",
      "consignment_number": "000000000008108353",
      "order_value": null,
      "tracking_url": "",
      "service": "Generic International Service",
      "carrier": "Generic Carrier",
      "rules_package_type": "",
      "shipping_date": null,
      "custom_field_1": "CUSTOM1",
      "custom_field_2": "CUSTOM2",
      "custom_field_3": "CUSTOM3",
      "custom_field_4": "CUSTOM4",
      "custom_field_5": "CUSTOM5",
      "export_customs": {}
    },
    {
      "identifier": "TEST5021",
      "order_number": "TEST5021",
      "create_date": "2017-05-24T12:03:41+0000",
      "expected_delivery_date": "2017-05-28",
      "service_id": "Generic Carrier|Generic International Service GCINT",
      "warehouse_id": "scurri-live-test|TechHub @Campus",
      "current_status": {
        "short_form": "Printed",
        "status": "Labels printed, shipment ready to manifest.",
        "rejection_reason": null
      },
      "recipient": {
        "name": "John Smith",
        "first_name": "",
        "last_name": "John Smith",
        "company_name": "Scurri",
        "email_address": "example-email@scurri.com",
        "contact_number": "0123456789",
        "address": {
          "address1": "Innovation House",
          "address2": "The Bullring",
          "address3": "",
          "city": "Wexford",
          "state": "Wexford",
          "postcode": "Y35 DW6E",
          "country": "IE",
          "store_code": ""
        },
        "tax_identifier": ""
      },
      "packages": [
        {
          "description": "Sample Product",
          "tracking_number": "9389534",
          "width": 1,
          "height": 3,
          "length": 3,
          "items": [
            {
              "name": "Sample Product",
              "quantity": 1,
              "sku": "PRO123",
              "country_of_origin": "GB",
              "harmonisation_code": "71131900",
              "weight": 2,
              "value": 32
            }
          ]
        }
      ],
      "invoice": {
        "incoterm": ""
      },
      "delivery_instructions": "Leave in the garden shed",
      "currency": "EUR",
      "options": {
        "package_type": null
      },
      "shipping_method": "",
      "consignment_number": "000000000008108335",
      "order_value": null,
      "tracking_url": "",
      "service": "Generic International Service",
      "carrier": "Generic Carrier",
      "rules_package_type": "",
      "shipping_date": null,
      "custom_field_1": "CUSTOM1",
      "custom_field_2": "CUSTOM2",
      "custom_field_3": "CUSTOM3",
      "custom_field_4": "CUSTOM4",
      "custom_field_5": "CUSTOM5",
      "export_customs": {}
    },
    {
      "identifier": "TEST5146",
      "order_number": "TEST5146",
      "create_date": "2017-05-24T12:03:36+0000",
      "expected_delivery_date": "2017-05-28",
      "service_id": "Generic Carrier|Generic International Service GCINT",
      "warehouse_id": "scurri-live-test|TechHub @Campus",
      "current_status": {
        "short_form": "Printed",
        "status": "Labels printed, shipment ready to manifest.",
        "rejection_reason": null
      },
      "recipient": {
        "name": "John Smith",
        "first_name": "",
        "last_name": "John Smith",
        "company_name": "Scurri",
        "email_address": "example-email@scurri.com",
        "contact_number": "0123456789",
        "address": {
          "address1": "Innovation House",
          "address2": "The Bullring",
          "address3": "",
          "city": "Wexford",
          "state": "Wexford",
          "postcode": "Y35 DW6E",
          "country": "IE",
          "store_code": ""
        },
        "tax_identifier": ""
      },
      "packages": [
        {
          "description": "Sample Product",
          "tracking_number": "9389522",
          "width": 1,
          "height": 1,
          "length": 2,
          "items": [
            {
              "name": "Sample Product",
              "quantity": 1,
              "sku": "PRO123",
              "country_of_origin": "GB",
              "harmonisation_code": "71131900",
              "weight": 0,
              "value": 69
            }
          ]
        }
      ],
      "invoice": {
        "incoterm": ""
      },
      "delivery_instructions": "Leave in the garden shed",
      "currency": "EUR",
      "options": {
        "package_type": null
      },
      "shipping_method": "",
      "consignment_number": "000000000008108323",
      "order_value": null,
      "tracking_url": "",
      "service": "Generic International Service",
      "carrier": "Generic Carrier",
      "rules_package_type": "",
      "shipping_date": null,
      "custom_field_1": "CUSTOM1",
      "custom_field_2": "CUSTOM2",
      "custom_field_3": "CUSTOM3",
      "custom_field_4": "CUSTOM4",
      "custom_field_5": "CUSTOM5",
      "export_customs": {}
    },
    {
      "identifier": "TEST5838",
      "order_number": "TEST5838",
      "create_date": "2017-05-24T12:03:32+0000",
      "expected_delivery_date": "2017-05-28",
      "service_id": "Generic Carrier|Generic International Service GCINT",
      "warehouse_id": "scurri-live-test|TechHub @Campus",
      "current_status": {
        "short_form": "Printed",
        "status": "Labels printed, shipment ready to manifest.",
        "rejection_reason": null
      },
      "recipient": {
        "name": "John Smith",
        "first_name": "",
        "last_name": "John Smith",
        "company_name": "Scurri",
        "email_address": "example-email@scurri.com",
        "contact_number": "0123456789",
        "address": {
          "address1": "Innovation House",
          "address2": "The Bullring",
          "address3": "",
          "city": "Wexford",
          "state": "Wexford",
          "postcode": "Y35 DW6E",
          "country": "IE",
          "store_code": ""
        },
        "tax_identifier": ""
      },
      "packages": [
        {
          "description": "Sample Product",
          "tracking_number": "9389516",
          "width": 1,
          "height": 1,
          "length": 2,
          "items": [
            {
              "name": "Sample Product",
              "quantity": 3,
              "sku": "PRO123",
              "country_of_origin": "GB",
              "harmonisation_code": "71131900",
              "weight": 3,
              "value": 2
            }
          ]
        }
      ],
      "invoice": {
        "incoterm": ""
      },
      "delivery_instructions": "Leave in the garden shed",
      "currency": "EUR",
      "options": {
        "package_type": null
      },
      "shipping_method": "",
      "consignment_number": "000000000008108317",
      "order_value": null,
      "tracking_url": "",
      "service": "Generic International Service",
      "carrier": "Generic Carrier",
      "rules_package_type": "",
      "shipping_date": null,
      "custom_field_1": "CUSTOM1",
      "custom_field_2": "CUSTOM2",
      "custom_field_3": "CUSTOM3",
      "custom_field_4": "CUSTOM4",
      "custom_field_5": "CUSTOM5",
      "export_customs": {}
    }
  ]
}

### Create a New Consignment [POST]

You can use this API call to create one or more new consignments. In
both cases, you have to specify a list in the body.

Scurri will do its best to store the data in the database and return a
successful message, instead of validating the data against a carrier.
That is, the validation process with a carrier is a step performed
after a consignment has been created successfully.  The reason is that
this way Scurri can decouple importing consignment data from allocating
it to a specific carrier, each of which has different requirements.

What this means in practice is that a success response for this API
call does not mean that the consignment has been allocated to a
carrier and service successfully.

Additionally, most users will want their configured rules to
allocate a consignment to a carrier and service. These users should
leave the carrier-related fields empty. If any of those are specified
in the request, then they will override the allocation made by rules.

Rules are always executed against your consignment data during the
allocation phase.

Another thing to keep in mind is that, in the case of batch creating
consignments, Scurri will run any allocation processes
asynchronously. As a result, a label will not be available straight
away. If your request contains data only for a single consignment then
the allocation happens synchronously.

If you need a way to associate your internal packages with Scurri packages,
please use the key `reference` that is available for each `package`.

The `reference` don't need to be unique per company or per item.

Finally, some carriers support enhancements and carrier-specific options which
must be specified in the "options" field, in example: Signed Consignments
("signed") or Package Type ("package_type").

You can take a look at the
[GET consignment](#reference/consignments/consignments/get-a-single-consignment)
for the payload of this request.

Max field lengths may be carrier dependant.

+ Request (application/json)

    + Attributes

        + identifier: 345334 (string,optional) - The consignment identifier in Scurri - must be unique across all of Scurri. If not provided, Scurri will provide one.
        + order_number: 7347382 (string,required) - The order number for the consignment.
        + create_date: `2019-02-28T10:43:44` (string,optional) - The date the order was placed.
            Must be in Timestamp format.
        + expected_delivery_date: `2019-03-10` (string,optional) - The promise delivery date for a shipment. Must be in Timestamp format (date).
        + carrier: Royal Mail (string,optional) - The carrier this consignment is to be shipped with.
        + service_id: Royal Mail | Tracked 48 (string,optional) - The service the carrier will use to ship the consignment.
        + warehouse_id: Company | London Warehouse (string,optional) - The warehouse in Scurri to ship the consignment from.
        + `shipping_method`: `uk_next_day` (string,optional) - The shipping method to be used in Scurri for the consignment which can be used with the Scurri rules engine.
           Field length: `255`
        + shipping_date: `2019-02-28` (string,optional) - The date that the shipment is expected to be dispatched.
        + order_value: 100.00 (number,optional) - The total order value for the Consignment in Scurri. (If not provided, this will be the sum of item values)
        + currency: GBP (string,optional) - The currency of the overall value of the consignment and the item’s value within the consignment.
            + Default: `GBP`
        + delivery_instructions: Leave in porch (string,optional) - The instructions provided by the consumer for the carrier.
        + origin_order_reference: `ABC-123` (string,optional) - Reference identifier of the origin system (mandatory for Amazon SFP shipments)
        + custom_field_1:(enum,optional) - A custom field that takes a string or number to be used in the Scurri rules engine. Field length: `255`
            + `Custom field for item 1` (string)
            + 2.99 (number)
        + custom_field_2:(enum,optional) - A second custom field that takes a string or number to be used in the Scurri rules engine. Field length: `255`
            + `Custom field for item 2` (string)
            + 2.99 (number)
        + custom_field_3:(enum,optional) - A third custom field that takes a string or number to be used in the Scurri rules engine. It's only available for certain tiers. Contact support for more details. Field length: `255`
            + `Custom field for item 3` (string)
            + 2.99 (number)
        + custom_field_4:(enum,optional) - A fourth custom field that takes a string or number to be used in the Scurri rules engine. It's only available for certain tiers. Contact support for more details. Field length: `255`
            + `Custom field for item 4` (string)
            + 2.99 (number)
        + custom_field_5:(enum,optional) - A fifth custom field that takes a string or number to be used in the Scurri rules engine. It's only available for certain tiers. Contact support for more details. Field length: `255`
            + `Custom field for item 5` (string)
            + 2.99 (number)
        + packages (array)
            + (object)
                + description: `Jeans` (string,optional) - Description of the package.
                    Field length: `255`
                + reference: `CustomCustomerReference1` (string,optional) - The package reference.
                    Field length: `255`
                + width: `12.2` (number,optional) - Width of the package in cm.
                + height: `0.5` (number,optional) - Height of the package in cm.
                + length: `10` (number,optional) - Length of the package in cm.
                + weight: `1` (number,optional) - Weight of the package in kg.
                    (If not provided, this will be the sum of item weights within the package)
                + items (array)
                    + (object)
                        + name: `Blue Jeans` (string,required) - The item name.
                            Field length: `255`
                        + quantity: `822 JEANS` (number,required) - The quantity of the item.
                        + sku: `Blue Jeans` (string,optional) - The items SKU.
                            Field length: `255`
                        + country_of_origin: `GB` (string,optional) - The country of origin.
                        + harmonisation_code: `5201` (string,optional) - The items harmonisation code (also known as HS code or commodity code).
                        + fabric_content: `silk` (string,optional) - The type of fabric used in the item. It should be only supplied when shipping textiles and apparel. It's only available by request. Contact support for more details.
                        + weight: `1` (number,optional) - The weight of the item in kg.
                        + value: `25.50` (number,optional) - The value of the item.
                        + taric_condition: `YX55` (string,optional) - The taric code of the item.
                        + reference: `ABC-123` (string,optional) - Reference identifier of the item (mandatory for Amazon SFP shipments).
        + recipient
            + name: `John Doe` (string,optional) - The full name of the recipient.
                Field length: `255`
            + first_name: `John` (string,optional) - The recipient's first name.
                Field length: `255`
            + last_name: `Doe` (string,optional) - The recipient’s last name.
                required if company_name or name are not provided.
                Field length: `255`
            + company_name: `Scurri Web Services` (string,optional) - The recipients’ company name.
                required if last_name or name are not provided
                Field length: `255`
            + email_address: `johndoe@scurri.com` (string,optional) - The recipient’s email address.
            + contact_number: `072 8848292234` (string,optional) - The recipient’s phone/contact number.
                Field length: `40`
            + tax_identifier: `12345665432` (string,optional) - The recipient’s tax identifier.
            + eori_number: `GB9876543210000` (string,optional) - The recipient’s EORI number.
                Field length: `15`
            + address
                + address1: `4-5 Bonhill Street` (string,required) - The destination first address line.
                    Field length: `255`
                + address2: `Shoreditch` (string,optional) - The destination second address line.
                    Field length: `100`
                + address3: `Finsbury` (string,optional) - The destination third address line.
                    Field length: `100`
                + city: `London` (string,required) - The destination city.
                    Field length: `100`
                + state: `London` (string,optional) - The destination state/county.
                    Field length: `100`
                + postcode: `EC2A4BX` (string,optional) - The destination postcode.
                    Field length: `100`
                + country: `United Kingdom` (string,required) - The destination country.
                + store_code: `45` (string,optional) - The store code collection number for pick-up drop-off services.
                    Field length: `50`
        + export_customs - Only include field if the value is populated, do not include if the value is null/empty.
            + reason_for_export: (enum,optional) - The reason for export or purpose of shipment for customs clearance.
            Must be chosen from the list below:
                + Default: `merchandise`
                + `merchandise`
                + `sample`
                + `documents`
                + `gift`
                + `other`
                + `returns`
                + `personal`
            + shipping_cost: `5.50` (number,optional) - The cost of shipping passed on to your customer.
            + ioss_number: `IMIRL1234567` (string,optional) - The IOSS number associated with the shipment if applicable.
                Field length: `12`
        + options : (object) - required if you are not using Scurri rules to allocate Carrier, Service and Enhancements.
        + invoice - required if you are not using Scurri rules to allocate Carrier, Service and Enhancements.
            + incoterm: `DDP` (string,optional) - The trade term associated with the shipment.
        + custom_attributes - Fields must be enabled by Scurri support.
            + override_sender_name: `TestCo` (string,optional) - The sender name to appear on the label.
            + override_sender_eori: `000123123GB` (string,optional) - The EORI that you want to use on the shipment .
            + override_sender_address1: `71 Test Street` (string,required) - First address line. Override sender address needs to be enabled by Scurri support.
            + override_sender_address2: `Test address 2 line` (string,optional) - Second address line.
            + override_sender_address3: `Test address 3 line` (string,optional) - Third address line.
            + override_sender_city: `Leeds` (string,required) - The city name of the sender.
            + override_sender_state: `West Yorkshire` (string,optional) - State/county of the sender.
            + override_sender_postcode: `BD1 1AA` (string,required) - Postcode of the sender.
            + override_sender_country: `GB` (string,required) - The country code of the sender. Use ISO codes here.
            + override_sender_email: `test@example.com` (string,optional) - The email address of the sender. If not provided the Warehouse/Company value will be used.
            + override_sender_phone: `+44 7975 777 666` (string,optional) - The phone number of the sender. If not provided the Warehouse/Company value will be used.

    + Headers

            Authorization: Basic YXBpdGVzdDphcGkgcGFzc3dvcmQgdGVzdA==

    + Body
        [
            {
                "identifier": "",
                "order_number": "8384832",
                "create_date": "2020-02-20T11:48:03+0000",
                "expected_delivery_date": "2020-02-28",
                "carrier": "",
                "service_id": "",
                "warehouse_id": "",
                "shipping_method": "shipping_method",
                "shipping_date": "",
                "order_value": 10.0,
                "currency": "",
                "delivery_instructions": "",
                "custom_field_1": "",
                "custom_field_2": "",
                "custom_field_3": "",
                "custom_field_4": "",
                "custom_field_5": "",
                "packages": [
                    {
                        "description": "Jeans",
                        "reference": "CustomCustomerReference1",
                        "width": 12.2,
                        "height": 0.5,
                        "length": 10,
                        "weight": 1,
                        "items": [
                            {
                                "name": "Jeans",
                                "quantity": 1,
                                "sku": "822 JEANS",
                                "country_of_origin": "GB",
                                "harmonisation_code": "5201",
                                "fabric_content": "cotton",
                                "weight": 1,
                                "value": 25.55,
                                "taric_condition": "YX55"
                            },
                            {
                                "name": "Jeans",
                                "quantity": 1,
                                "sku": "823 JEANS",
                                "country_of_origin": "GB",
                                "harmonisation_code": "5201",
                                "fabric_content": "cotton",
                                "weight": 1,
                                "value": 25.55
                            }
                        ]
                    },
                    {
                        "description": "Jeans",
                        "reference": "CustomCustomerReference2",
                        "width": 12.2,
                        "height": 0.5,
                        "length": 10,
                        "weight": 1,
                        "items": [
                            {
                                "name": "Jeans",
                                "quantity": 1,
                                "sku": "824 JEANS",
                                "country_of_origin": "GB",
                                "harmonisation_code": "5201",
                                "fabric_content": "cotton",
                                "weight": 1,
                                "value": 25.55
                            },
                            {
                                "name": "Jeans",
                                "quantity": 1,
                                "sku": "824 JEANS",
                                "country_of_origin": "GB",
                                "harmonisation_code": "5201",
                                "fabric_content": "cotton",
                                "weight": 1,
                                "value": 25.55
                            }
                        ]
                    }
                ],
                "recipient": {
                    "name": "John Doe",
                    "first_name": "",
                    "last_name": "",
                    "company_name": "",
                    "email_address": "johndoe@johndoe.com",
                    "contact_number": "07827904687",
                    "tax_identifier": "123456",
                    "eori_number": "GB123456789123",
                    "address": {
                        "address1": "77  Crown Street",
                        "address2": "",
                        "address3": "",
                        "city": "London",
                        "state": "",
                        "postcode": "SW1H 8ZW",
                        "country": "GB",
                        "store_code": ""
                    }
                },
                "export_customs": {
                    "reason_for_export": "merchandise",
                    "shipping_cost": "10.00",
                    "ioss_number": "IMIRL1234567"
                },
                "custom_attributes": {
                    "override_sender_name": "TestCo",
                    "override_sender_eori": "0000123123GB",
                    "override_sender_address1": "71 Test Street",
                    "override_sender_address2": "Test address 2 line",
                    "override_sender_address3": "Test address 3 line",
                    "override_sender_city": "Leeds",
                    "override_sender_state": "West Yorkshire",
                    "override_sender_postcode": "BD1 1AA",
                    "override_sender_country": "GB",
                    "override_sender_email": "test@example.com",
                    "override_sender_phone": "+44 7975 777 666"
                },
                "options": {},
                "invoice": {
                    "incoterm": ""
                }
            }
        ]

+ Response 201 (application/json)

    The response has 2 entries: one is a dictionary for errors and one
    a list of successful imports.

    + Body

        {
            "errors": {},
            "success": [
                "8a12630db404424b943e131ce4ee3976"
            ]
        }

+ Response 400 (application/json)

    Error example where quantity is a mandatory field and not provided.

    + Body

        {
            "errors": {
                "0": [
                    "packages: items: quantity: This field is required."
                ]
            },
            "success": []
        }

## Consignments [/company/{company_slug}/consignment/{consignment_id}/]

+ Parameters
    + company_slug: `api-test-company` (string) - The slug of your company in Scurri.
    + consignment_id (string) - The consignment identifier for the consignment


#### Get a single consignment [GET]

You can use this API call to get all details for the specified
consignment.

For instance, this is how you can query the status of a consignment
and get any error messages from the allocation phase.

`status` indicates the status of a consignment e.g. `Printed - ready to manifest`.\
`short_form` provides a shortened version of `status` e.g `Printed`.\
`rejection_reason` only applies where the shipment status is `Unallocated`.

+ Request (application/json)
    + Headers

            Authorization: Basic YXBpdGVzdDphcGkgcGFzc3dvcmQgdGVzdA==

+ Response 200 (application/json)

    The response has the details of the specified consignment.

    + Body

            {
                "carrier": "Generic Carrier",
                "consignment_number": null,
                "create_date": "2016-03-28T11:53:31+0000",
                "expected_delivery_date": null,
                "currency": "GBP",
                "current_status": {
                    "rejection_reason": null,
                    "short_form": "Allocated",
                    "status": "Carrier and service allocated"
                },
                "delivery_instructions": "",
                "identifier": "8a12630db404424b943e131ce4ee3976",
                "invoice": {
                    "incoterm": ""
                },
                "options": {
                    "package_type": null
                },
                "order_number": "8384832",
                "order_value": null,
                "packages": [
                    {
                        "description": "Jeans",
                        "reference": "CustomCustomerReference1",
                        "height": 0.5,
                        "items": [
                            {
                                "country_of_origin": "GB",
                                "harmonisation_code": "5201",
                                "name": "Jeans",
                                "quantity": 1,
                                "sku": "822 JEANS",
                                "value": 25.55,
                                "weight": 1.0
                            }
                        ],
                        "length": 10.0,
                        "tracking_number": null,
                        "width": 12.2
                    }
                ],
                "recipient": {
                    "address": {
                        "address1": "Innovation House",
                        "address2": "The Bullring",
                        "address3": "",
                        "city": "Wexford",
                        "country": "IE",
                        "postcode": "Y35 DW6E",
                        "state": "Wexford",
                        "store_code": ""
                    },
                    "company_name": "Scurri",
                    "contact_number": "072 8848292234",
                    "email_address": "john@scurri.com",
                    "first_name": "",
                    "last_name": "John Doe",
                    "name": "John Doe"
                },
                "rules_package_type": "<ShipmentDomain(44147)>",
                "service": "Generic International Service",
                "service_id": "Generic Carrier|Generic International Service GCINT",
                "shipping_method": "",
                "tracking_url": "",
                "warehouse_id": "company-slug|Warehouse Name"
            }

+ Response 200 (application/json)

    Example response with an unallocated consignment.

    + Body

        {
            "identifier": "e0156b67b4f64000b7f02a10b712c7ed",
            "order_number": "220804-001",
            "create_date": "2022-08-04T15:21:12+0000",
            "expected_delivery_date": null,
            "service_id": "Generic Carrier|Generic Domestic Service GDOM",
            "warehouse_id": "generic-account|Generic WH IE",
            "current_status": {
                "short_form": "Unallocated",
                "status": "Label not available",
                "rejection_reason": "Division required for country IE"
            },
            "recipient": {
                "name": "",
                "first_name": "John",
                "last_name": "Doe",
                "company_name": "",
                "email_address": "test@anon.com",
                "contact_number": "12345678",
                "address": {
                    "address1": "Common Quay St",
                    "address2": "Ferrybank South",
                    "address3": "",
                    "city": "Wexford",
                    "state": "",
                    "postcode": "Y35 EK88",
                    "country": "IE",
                    "store_code": ""
                }
            }
        }

+ Response 200 (application/json)

    Example response with consignment ready to ship.

    + Body

        {
            "identifier": "a424b7303da74c85997fffcd2f95d716",
            "order_number": "220520-001",
            "create_date": "2022-05-20T11:46:43+0000",
            "expected_delivery_date": null,
            "service_id": "Generic Carrier|Generic Domestic Service GDOM",
            "warehouse_id": "generic-account|Generic WH IE",
            "current_status": {
                "short_form": "Printed",
                "status": "Labels printed, shipment ready to manifest.",
                "rejection_reason": null
            }
        }


    + Schema

            {
                "properties": {
                    "order_value": {
                    "description": "This is the total value of the order. If this is not specified, then Scurri will calculate it from the values of the items in the order.",
                    "type": "number",
                    "required": false,
                    "defaultValue": null
                },
                "options": {
                  "description": "Additional carrier-specific options for the consignment.This is also the place where you set service enhancements",
                  "required": false,
                  "defaultValue": null,
                  "properties": {
                    "package_type": {
                      "type": "string",
                      "minimum": null,
                      "maximum": null,
                      "required": false,
                      "defaultValue": null,
                      "description": "Package type to use for this consignment."
                    }
                  }
                },
                "order_number": {
                  "type": "string",
                  "minimum": null,
                  "maximum": null,
                  "required": true,
                  "defaultValue": null,
                  "description": "Order number for the consignment"
                },
                "identifier": {
                  "type": "string",
                  "minimum": null,
                  "maximum": null,
                  "required": false,
                  "defaultValue": null,
                  "description": "A unique identifier, chosen by the client. If no identifier is given, a unique identifier is auto-generated. Note that if recreating the consignment by cancelling and creating again, the recreated identifier MUST be new and unique. Cancelled consignments retain their identifier so the identifier cannot be reused"
                },
                "service_id": {
                  "type": "string",
                  "minimum": null,
                  "maximum": null,
                  "required": false,
                  "defaultValue": null,
                  "description": "Carrier service ID that has been assigned to the consignment. Note that this takes precedence over any service assigned via shipping_method"
                },
                "delivery_instructions": {
                  "type": "string",
                  "minimum": null,
                  "maximum": null,
                  "required": false,
                  "defaultValue": null,
                  "description": "Any delivery or customer notes for the consignment"
                },
                "invoice": {
                  "description": "Customs data for the consignment. Only required for international consignments",
                  "required": true,
                  "defaultValue": null,
                  "properties": {
                    "incoterm": {
                      "type": "string",
                      "minimum": null,
                      "maximum": null,
                      "required": true,
                      "defaultValue": null,
                      "description": "The terms of delivery for international consignments",
                      "enum": [
                        "",
                        "DDP",
                        "DAP"
                      ]
                    }
                  }
                },
                "consignment_number": {
                  "type": "string",
                  "minimum": null,
                  "maximum": null,
                  "required": false,
                  "defaultValue": null,
                  "description": "The consignment number"
                },
                "currency": {
                  "type": "string",
                  "minimum": null,
                  "maximum": null,
                  "required": false,
                  "defaultValue": null,
                  "description": "ISO 4217 code for the currency used with the consignment. If not specified, defaults to British pounds (GBP)"
                },
                "carrier": {
                  "type": "string",
                  "minimum": null,
                  "maximum": null,
                  "required": false,
                  "defaultValue": null,
                  "description": "Carrier name"
                },
                "warehouse_id": {
                  "type": "string",
                  "minimum": null,
                  "maximum": null,
                  "required": false,
                  "defaultValue": null,
                  "description": "Warehouse ID where the consignment is being processed. It's composed by the company slug and the warehouse name"
                },
                "current_status": {
                  "description": "Current status of the consignment. Read-only",
                  "required": false,
                  "defaultValue": null,
                  "properties": {
                    "short_form": {
                      "type": "string",
                      "minimum": null,
                      "maximum": 255,
                      "required": true,
                      "defaultValue": null,
                      "description": "shortened name of status",
                      "enum": [
                        "Unallocated",
                        "Allocated",
                        "Printed",
                        "Manifested",
                        "Despatched",
                        "Cancelled"
                      ]
                    },
                    "rejection_reason": {
                      "type": "string",
                      "minimum": null,
                      "maximum": null,
                      "required": false,
                      "defaultValue": null,
                      "description": "additional information regarding unallocated status"
                    },
                    "status": {
                      "type": "string",
                      "minimum": null,
                      "maximum": 255,
                      "required": true,
                      "defaultValue": null,
                      "description": "message describing current status"
                    }
                  }
                },
                "tracking_url": {
                  "type": "string",
                  "minimum": null,
                  "maximum": null,
                  "required": false,
                  "defaultValue": null,
                  "description": "The tracking url"
                },
                "recipient": {
                  "description": "Recipient address information",
                  "required": true,
                  "defaultValue": null,
                  "properties": {
                    "email_address": {
                      "type": "string",
                      "minimum": null,
                      "maximum": null,
                      "required": false,
                      "defaultValue": null,
                      "description": "E-mail address for the contact. Required depending on carrier"
                    },
                    "address": {
                      "description": "Address information for the contact",
                      "required": true,
                      "defaultValue": null,
                      "properties": {
                        "country": {
                          "type": "string",
                          "minimum": null,
                          "maximum": null,
                          "required": true,
                          "defaultValue": null,
                          "description": "ISO 3166-1 alpha-2 country code for the address"
                        },
                        "postcode": {
                          "type": "string",
                          "minimum": null,
                          "maximum": null,
                          "required": false,
                          "defaultValue": null,
                          "description": "address postal code. Required for most countries"
                        },
                        "state": {
                          "type": "string",
                          "minimum": null,
                          "maximum": null,
                          "required": false,
                          "defaultValue": null,
                          "description": "state/county/prefecture code. Required for certain countries"
                        },
                        "address3": {
                          "type": "string",
                          "minimum": null,
                          "maximum": null,
                          "required": false,
                          "defaultValue": null,
                          "description": "Street address (line 3) for the location"
                        },
                        "address2": {
                          "type": "string",
                          "minimum": null,
                          "maximum": null,
                          "required": false,
                          "defaultValue": null,
                          "description": "Street address (line 2) for the location"
                        },
                        "address1": {
                          "type": "string",
                          "minimum": null,
                          "maximum": null,
                          "required": true,
                          "defaultValue": null,
                          "description": "Street address (line 1) for the location"
                        },
                        "store_code": {
                          "type": "string",
                          "minimum": null,
                          "maximum": null,
                          "required": false,
                          "defaultValue": null,
                          "description": "The identifier of the drop off location (Collect+ etc)"
                        },
                        "city": {
                          "type": "string",
                          "minimum": null,
                          "maximum": 100,
                          "required": true,
                          "defaultValue": null,
                          "description": "address name of the city"
                        }
                      }
                    },
                    "company_name": {
                      "type": "string",
                      "minimum": null,
                      "maximum": null,
                      "required": false,
                      "defaultValue": null,
                      "description": "Name of the contact's company"
                    },
                    "first_name": {
                      "type": "string",
                      "minimum": null,
                      "maximum": null,
                      "required": true,
                      "defaultValue": null,
                      "description": "First name part of the full name."
                    },
                    "name": {
                      "type": "string",
                      "minimum": null,
                      "maximum": null,
                      "required": true,
                      "defaultValue": null,
                      "description": "Full name of the contact"
                    },
                    "last_name": {
                      "type": "string",
                      "minimum": null,
                      "maximum": null,
                      "required": true,
                      "defaultValue": null,
                      "description": "Last name part of the full name."
                    },
                    "contact_number": {
                      "type": "string",
                      "minimum": null,
                      "maximum": null,
                      "required": false,
                      "defaultValue": null,
                      "description": "Landline/mobile number for contact. Required depending on carrier"
                    }
                  }
                },
                "rules_package_type": {
                  "type": "string",
                  "minimum": null,
                  "maximum": null,
                  "required": false,
                  "defaultValue": null,
                  "description": "Package type to use in rules"
                },
                "custom_field_1": {
                  "type": "string",
                  "minimum": null,
                  "maximum": null,
                  "required": false,
                  "defaultValue": null,
                  "description": "First custom field"
                },
                "custom_field_2": {
                  "type": "string",
                  "minimum": null,
                  "maximum": null,
                  "required": false,
                  "defaultValue": null,
                  "description": "Second custom field"
                },
                "custom_field_3": {
                  "type": "string",
                  "minimum": null,
                  "maximum": null,
                  "required": false,
                  "defaultValue": null,
                  "description": "Third custom field"
                },
                "custom_field_4": {
                  "type": "string",
                  "minimum": null,
                  "maximum": null,
                  "required": false,
                  "defaultValue": null,
                  "description": "Fourth custom field"
                },
                "custom_field_5": {
                  "type": "string",
                  "minimum": null,
                  "maximum": null,
                  "required": false,
                  "defaultValue": null,
                  "description": "Fifth custom field"
                },
                "service": {
                  "type": "string",
                  "minimum": null,
                  "maximum": null,
                  "required": false,
                  "defaultValue": null,
                  "description": "Service name"
                },
                "shipping_method": {
                  "type": "string",
                  "minimum": null,
                  "maximum": null,
                  "required": false,
                  "defaultValue": null,
                  "description": "Optional shipping method for the consignment"
                },
                "create_date": {
                  "description": "Optional ISO 8601 date/time the consignment was created. If not specified, defaults to current date/time. If timezone offset not specified, defaults to UTC offset",
                  "type": "string",
                  "required": false,
                  "defaultValue": null
                },
                "expected_delivery_date": {
                  "description": "Optional ISO 8601 date the consignment was promised to be delivered. If not specified, defaults to null.",
                  "type": "string",
                  "required": false,
                  "defaultValue": null
                },
                "shipping_date": {
                  "description": "Optional ISO 8601 date/time the shipping will take place. If not specified, defaults to date of printing. If timezone offset not specified, defaults to UTC offset",
                  "type": "string",
                  "required": false,
                  "defaultValue": null
                },
                "packages": {
                  "description": "Packages for the consignment",
                  "type": "array",
                  "required": true,
                  "defaultValue": null,
                  "items": {
                    "properties": {
                      "tracking_number": {
                        "type": "string",
                        "minimum": null,
                        "maximum": null,
                        "required": false,
                        "defaultValue": null,
                        "description": "unique identifier assigned by the carrier for tracking the package, if per-package tracking is supported. Read-only"
                      },
                      "width": {
                        "description": "unit width of the package",
                        "type": "number",
                        "required": true,
                        "defaultValue": null
                      },
                      "height": {
                        "description": "unit height of the package",
                        "type": "number",
                        "required": true,
                        "defaultValue": null
                      },
                      "length": {
                        "description": "unit length of the package",
                        "type": "number",
                        "required": true,
                        "defaultValue": null
                      },
                      "items": {
                        "description": "Items contained in the package",
                        "type": "array",
                        "required": true,
                        "defaultValue": null,
                        "items": {
                          "properties": {
                            "quantity": {
                              "description": "Number of items in the package",
                              "type": "integer",
                              "required": true,
                              "default": 1
                            },
                            "value": {
                              "description": "unit value of the item",
                              "type": "number",
                              "required": true,
                              "defaultValue": null
                            },
                            "harmonisation_code": {
                              "type": "string",
                              "minimum": null,
                              "maximum": 35,
                              "required": false,
                              "defaultValue": null,
                              "description": "Standard harmonisation code of the item for tariff purposes. Only required if sending to an international destination."
                            },
                            "weight": {
                              "description": "weight of the item",
                              "type": "number",
                              "required": true,
                              "defaultValue": null
                            },
                            "name": {
                              "type": "string",
                              "minimum": null,
                              "maximum": 255,
                              "required": false,
                              "defaultValue": null,
                              "description": "display name of the item"
                            },
                            "country_of_origin": {
                              "type": "string",
                              "minimum": null,
                              "maximum": null,
                              "required": true,
                              "defaultValue": null,
                              "description": "ISO 3166-1 alpha-2 country code from where the item originates"
                            },
                            "sku": {
                              "type": "string",
                              "minimum": null,
                              "maximum": 255,
                              "required": false,
                              "defaultValue": null,
                              "description": "SKU for the item"
                            }
                          },
                          "required": [
                            "country_of_origin",
                            "weight",
                            "value",
                            "quantity"
                          ],
                          "description": "Defines item data for a specific package. A package may have one or more\nitems. Weight is always defined in kilograms."
                        }
                      },
                      "description": {
                        "type": "string",
                        "minimum": null,
                        "maximum": null,
                        "required": true,
                        "defaultValue": null,
                        "description": "general description of the contents of the package"
                      }
                    },
                    "required": [
                      "description",
                      "items",
                      "length",
                      "height",
                      "width"
                    ],
                    "description": "Defines package data for a specific consignment. Dimensions are all in\ncentimetres."
                  }
                }
              },
              "required": [
                "packages",
                "recipient",
                "invoice",
                "order_number"
              ]
            }

+ Response 404 (application/json)

    This response indicates that the consignment has not been found.

    + Body

        {
            "detail": "Not found."
        }

#### Update the specified consignment [PUT]

You can use this API call to update the details of the specified consignment.

The API does not support partial updates, you must specify all values when using this API call.

Mandatory and optional fields are detailed under the [Create a New Consignment](#reference/consignments/consignments-collection/create-a-new-consignment) call.

+ Request (application/json)
    + Headers

            Authorization: Basic YXBpdGVzdDphcGkgcGFzc3dvcmQgdGVzdA==

    + Body

            {
              "carrier": "Generic Carrier",
              "warehouse_id": "company-slug|Warehouse Name",
              "service_id": "Generic Carrier|Generic International Service GCINT",
              "identifier": "8a12630db404424b943e131ce4ee3976",
              "packages": [
                {
                  "items": [
                    {
                      "weight": 1.0,
                      "value": 25.55,
                      "fabric_content": "silk",
                      "harmonisation_code": "5201",
                      "country_of_origin": "GB",
                      "sku": "822 JEANS",
                      "quantity": 2,
                      "name": "Jeans"
                    }
                  ],
                  "length": 10.0,
                  "height": 0.5,
                  "width": 12.2,
                  "reference": "CustomCustomerReference1"
                }
              ],
              "recipient": {
                "address": {
                  "country": "IE",
                  "postcode": "Y35 DW6E",
                  "city": "Wexford",
                  "address2": "The Bullring",
                  "address1": "Innovation House",
                  "state": "Wexford"
                },
                "contact_number": "072 8848292234",
                "email_address": "john@scurri.com",
                "company_name": "Scurri",
                "name": "John Doe"
              },
              "order_number": "8384832",
              "options": {
                "package_type": "Bag",
                "signed": "No"
              }
            }

+ Response 200 (application/json)

    The response includes all information for the updated consignment;
    that is, the result is the same as that of a `GET` request.

    + Body

            {
                "carrier": "Generic Carrier",
                "consignment_number": null,
                "create_date": "2016-03-28T12:57:05+0000",
                "expected_delivery_date": null,
                "currency": "GBP",
                "current_status": {
                    "rejection_reason": null,
                    "short_form": "Allocated",
                    "status": "Carrier and service allocated"
                },
                "delivery_instructions": "",
                "identifier": "8a12630db404424b943e131ce4ee3976",
                "invoice": {
                    "incoterm": ""
                },
                "options": {
                    "package_type": null
                },
                "order_number": "8384832",
                "order_value": null,
                "packages": [
                    {
                        "description": "Jeans",
                        "reference": "CustomCustomerReference1",
                        "height": 0.5,
                        "items": [
                            {
                                "country_of_origin": "GB",
                                "harmonisation_code": "5201",
                                "name": "Jeans",
                                "quantity": 2,
                                "sku": "822 JEANS",
                                "value": 25.55,
                                "weight": 1.0
                            }
                        ],
                        "length": 10.0,
                        "tracking_number": null,
                        "width": 12.2
                    }
                ],
                "recipient": {
                    "address": {
                        "address1": "Innovation House",
                        "address2": "The Bullring",
                        "address3": "",
                        "city": "Wexford",
                        "country": "IE",
                        "postcode": "Y35 DW6E",
                        "state": "Wexford",
                        "store_code": ""
                    },
                    "company_name": "Scurri",
                    "contact_number": "072 8848292234",
                    "email_address": "john@scurri.com",
                    "first_name": " ",
                    "last_name": "John Doe",
                    "name": "John Doe"
                },
                "rules_package_type": "Shipment 44148 : None",
                "service": "Generic International Service",
                "service_id": "Generic Carrier|Generic International Service GCINT",
                "shipping_method": "service_type",
                "tracking_url": "",
                "warehouse_id": "company-slug|Warehouse Name"
            }


+ Response 400 (application/json)

    This response indicates that something was wrong with the supplied
    data.

    + Body

        {
            "detail": "packages: items: quantity: This field is required."
        }

### Cancel a single consignment [DELETE]

You can use this API call to cancel a consignment. Scurri will notify,
when necessary, the carrier to void the generated labels.

+ Request (application/json)
    + Headers

            Authorization: Basic YXBpdGVzdDphcGkgcGFzc3dvcmQgdGVzdA==

+ Response 204

    This response indicates that the consignment was cancelled
    successfully.

    + Body

+ Response 400 (application/json)

    This response indications that there was an error cancelling the
    specified consignment.

    + Body

        {
            "detail": "Cannot cancel shipment with status of \"Cancelled at 2022-02-02 09:00:00.000000+00:00\""
        }


## Consignment Documents [/company/{company_slug}/consignment/{consignment_id}/documents/{?documenttype,label_quantity,invoice_quantity}]

### Get the label and the invoice for the consignment [GET]

You can use this API call to get the label and any customs invoice
documents required for a specific consignment, if required.

Keep in mind that a label will be created for each package of the
consignment.

#### Available label formats

The resulting documents are returned as strings within the JSON response. These are plaintext in the case of ZPL labels, all other formats are base64-encoded binary files. 
Labels can be provided in the following formats:
- PDF: One PDF returned with multiple labels concatenated in a single document (one label per page)
- PNG: A ZIP file is returned containing all files
- X-png-list: Single file PNGs (non-zipped)
- ZPL: Can be configured as 230 or 300 DPI resolution. It's also possible to specify the required label resolution or compress the label in the request.

Alternative label formats are also available, for example 8"x4". To enable this feature on your account, contact Scurri support. Once enabled the label customisation parameter can be used.

#### Customs Invoice Documents

About the customs invoice documents, Scurri will return the documents
the carrier requires, only if the carrier does require them for the
specific consignment.

Another thing to note about customs invoice documents is that they can
be either in a 6"x4" size (for thermal printer) or in an A4 size (for
a document printer). Your account can be configured, so that 6"x4"
thermal invoices can be concatenated with the respective label. This
makes it easier to send each file to the correct printer.

Note that setting documenttype to `application/x-zebra-zpl` only impacts labels, not invoices - they remain PDF as they are A4.

#### ZPL Supported Carriers


|||||
|:---:|:---:|:---:|:---:|
| An Post | Colissimo | Deutsche Post | DPD |
| DPD Germany | DPD Ireland | DX | Fastway |
| Generic Carrier | Hermes | Interlink | ITD Carrier |
| P2P Trakpak | ParcelForce | PostNL | Royal Mail |
| Spring Global | TNT | Tuffnells | UKMail |
| Yodel |  |  |  |
|||||


+ Parameters
    + company_slug: `api-test-company` (string) - The slug of your company in Scurri.
    + consignment_id (string) - The identifier of the consignment.
    + documenttype (enum[string],optional) - The file format of the result. The available values are `application/pdf`, `image/png` and `application/x-zebra-zpl`.

        + Default: `application/pdf`
        + Members
            + `application/pdf`
            + `image/png`
            + `application/x-zebra-zpl`

    + label_quantity (int,optional) - The number of copies of the label you want.
        + Default: 1
    + label_compression (boolean, optional) - Compress label documents. Available for the ZPL format.
        + Default: `false`
    + invoice_quantity (int,optional) - The number of copies for the customs invoice document you want.
        + Default: 3

+ Request
    + Headers

            Authorization: Basic YXBpdGVzdDphcGkgcGFzc3dvcmQgdGVzdA==

+ Response 200 (application/json)

    + Body

            {
                "invoices": null,
                "labels": "..."
            }

    + Schema

            {
              "properties": {
                "labels": {
                  "description": "Plaintext or Base64-encoded string containing label.",
                  "type": "string",
                  "required": true
                },
                "invoices": {
                  "description": "Base64-encoded string containing raw invoice bytes.",
                  "type": "string",
                  "required": false
                }
              },
              "description": "contains consignment documents data"
            }

+ Response 400 (application/json)

    This response indicates that there has been a problem with
    generating the documents. You should check the status of the
    consignment instead.

    + Body

        {
            "detail": "Consignment not ready for printing."
        }

+ Response 408 (application/json)

    This response indicates that there was a timeout, when Scurri tried to
    contact a carrier's servers. You should re-try fetching the documents.

    + Body


# Group Manifests

The manifest process marks a list of consignments as ready to be
picked up by the carrier.

A manifest always refers to a specific warehouse and carrier. Scurri
abstracts away the necessary actions and documentation a carrier needs
and presents a common interface for the manifest process.

## Creating Manifests [/company/{company_slug}/manifest/]

### Create a manifest [POST]

You can use this API call to mark a list of consignments for a
**specific carrier** and **specific warehouse** as manifested.

This API call will mark the specified consignments as manifested
within Scurri and perform any post-manifest actions, such as generate
the necessary documentation for a manifest and send any pre-alert data
to the carrier.

+ Parameters
    + company_slug: `api-test-company` (string) - The slug of your company in Scurri.
+ Request (application/json)
    + Headers

            Authorization: Basic YXBpdGVzdDphcGkgcGFzc3dvcmQgdGVzdA==

    + Body

            {
                "consignment_ids": [
                    "8a12630db404424b943e131ce4ee3976"
                ],
                "carrier_id": "Generic Carrier",
                "warehouse_id": "api-test-company|Test Warehouse"
            }

    + Schema

            {
              "properties": {
                "consignment_ids": {
                  "description": "Consignment IDs for the manifest. All consignments must be ready for manifesting.",
                  "type": "array",
                  "required": true,
                  "items": {
                    "type": "string"
                  }
                },
                "carrier_id": {
                  "description": "Carrier ID for the manifest",
                  "type": "string",
                  "required": true
                },
                "warehouse_id": {
                  "description": "Warehouse ID where the consignment is being manifested. It's composed by the company slug and the warehouse name. Defaults to the company's default warehouse if not specified",
                  "type": "string",
                  "required": false
                }
              },
              "description": "Data to send for creating a manifest."
            }


+ Response 201 (application/json)

    The shipments have been marked as manifested and the background
    jobs have been kicked off.

    + Body

            {
                "identifier": "2432"
            }

+ Response 400 (application/json)

    The request has some errors.

    + Body

        {
            "detail": "carrier_id: This field is required."
        }

## Manifest Documentation [/company/{company_slug}/manifest/{manifest_id}/documents/]

You can use this API call to get the manifest documentation (as an
A4-size PDF file) that you need to hand-in to the carrier.

Scurri will return the correct documentation for the specified
carrier.

Keep in mind that, because the document generation is kicked off
asynchronously by the previous API call, the documents may not be
ready, when you execute this API call. In that case, you should retry
after a while.

### Get the manifest documentation [GET]

+ Parameters
     + company_slug: `api-test-company` (string) - The slug of your company in Scurri.
     + manifest_id (int) - The identifier of the manifest, as returned by the previous API call.
+ Request (application/json)
    + Headers

            Authorization: Basic YXBpdGVzdDphcGkgcGFzc3dvcmQgdGVzdA==

+ Response 200 (application/json)

    The response contains the PDF documents as a base64-encoded
    string.

    + Body

            {
                "documents": "..."
            }

+ Response 204 (application/json)

    This response indicates that the documents are not ready yet.

    + Body

+ Response 400 (application/json)

    This response indicates that there was something wrong with the request.

    + Body

        {
            "detail": "consignment_ids: Consignment(s) not ready for manifesting"
        }

+ Response 409 (application/json)

    This response indicates that the manifesting process has failed.

    + Body